import { groq } from "@ai-sdk/groq";
import { generateObject } from "ai";
import { z } from "zod";
import prisma from "@/lib/db";
import { SecretsFilterService } from "./secrets-filter.service";

const AiAuthorshipSchema = z.object({
  authorshipConfidence: z
    .number()
    .min(0)
    .max(100)
    .describe(
      "Confidence score from 0 to 100 that this code was generated by AI rather than a human. 0 = definitely human, 100 = definitely AI.",
    ),
  reasoning: z
    .string()
    .describe(
      "Brief explanation of why this score was given, citing specific code patterns (e.g., variable naming, structure, idiomatic usage).",
    ),
});

export class AiOrchestratorService {
  private static PRIMARY_MODEL = "openai/gpt-oss-120b";
  private static FALLBACK_MODEL = "openai/gpt-oss-20b";

  /**
   * Evaluates a specific code diff to determine the likelihood it was AI-authored.
   * Enforces scoped context, secrets filtering, structured output, and cost controls.
   */
  static async evaluateAuthorship(
    organizationId: string,
    diffContent: string,
  ): Promise<number | null> {
    // 1. Check Rate Limits (T-4.2.5)
    const canMakeCall = await this.checkAndIncrementUsage(organizationId);
    if (!canMakeCall) {
      console.warn(
        `[AI Orchestrator] Org ${organizationId} has reached its monthly AI call limit.`,
      );
      return null;
    }

    // 2. Pre-filter Secrets (T-4.2.1)
    const safeDiff = SecretsFilterService.filter(diffContent);

    // 3. Prepare structured output call (T-4.2.3)
    const systemPrompt = `You are an expert software engineer analyzing code diffs. 
Your task is to determine the likelihood (0-100) that the provided code was written by an AI coding assistant (like GitHub Copilot, ChatGPT, or Claude) rather than a human.
Look for typical AI patterns: excessively verbose comments, overly literal variable names, lack of domain-specific idioms, or 'textbook' implementations of algorithms.`;

    const prompt = `Please analyze the following code diff and provide your assessment:\n\n${safeDiff}`;

    try {
      // 4. Primary Provider Call (T-4.1.2)
      const { object } = await generateObject({
        model: groq(this.PRIMARY_MODEL),
        schema: AiAuthorshipSchema,
        system: systemPrompt,
        prompt: prompt,
      });

      return object.authorshipConfidence;
    } catch (primaryError) {
      console.error(
        `[AI Orchestrator] Primary model (${this.PRIMARY_MODEL}) failed:`,
        primaryError,
      );

      // 5. Fallback Provider Call (T-4.2.4)
      console.log(
        `[AI Orchestrator] Attempting fallback model (${this.FALLBACK_MODEL})...`,
      );
      try {
        const { object } = await generateObject({
          model: groq(this.FALLBACK_MODEL),
          schema: AiAuthorshipSchema,
          system: systemPrompt,
          prompt: prompt,
        });

        return object.authorshipConfidence;
      } catch (fallbackError) {
        console.error(
          `[AI Orchestrator] Fallback model (${this.FALLBACK_MODEL}) also failed:`,
          fallbackError,
        );
        // Explicitly return null to indicate 'AI assessment unavailable' state
        return null;
      }
    }
  }

  /**
   * Ensures the organization hasn't exceeded its monthly API limit.
   * If allowed, increments the counter.
   * Returns true if the call is allowed, false otherwise.
   */
  private static async checkAndIncrementUsage(
    organizationId: string,
  ): Promise<boolean> {
    if (organizationId === "eval-test-org-id") {
      return true; // Bypass usage tracking for local evaluations
    }

    const currentMonth = new Date().toISOString().slice(0, 7); // e.g., "2026-08"

    const usageRecord = await prisma.aiUsage.upsert({
      where: {
        organizationId_month: {
          organizationId,
          month: currentMonth,
        },
      },
      update: {},
      create: {
        organizationId,
        month: currentMonth,
        callCount: 0,
        callLimit: 1000, // Default ceiling
      },
    });

    if (usageRecord.callCount >= usageRecord.callLimit) {
      return false; // Quota reached
    }

    // Increment usage
    await prisma.aiUsage.update({
      where: { id: usageRecord.id },
      data: { callCount: { increment: 1 } },
    });

    return true;
  }
}
